runtime: java11
env: standard
instance_class: F1

service: default

automatic_scaling:
  min_instances: 0
  max_concurrent_requests: 40
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 10s
  max_pending_latency: 15s

entrypoint: java -noverify -jar coronavirusapi*.war