# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

parameters:
  welcome:
    type: boolean
    default: false


jobs:
  welcome:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - when:
        condition: << pipeline.parameters.welcome >>
        steps:
          - run: echo 'welcome to the show'
      

  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: echo 'hola'

      - run: echo 'chaoo'

  deploy:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/repo

    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

      - checkout

      - run: echo 'hola'

      - run: echo 'chao'

workflows:
  version: 2

  build-deploy:
    jobs:
      - welcome  
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master