name: pull request alpha deploy
on:
  issue_comment:
    types: [created, edited]

jobs:
  deploy-alpha:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/alpha')
    runs-on: [ubuntu-latest]
    steps:
      - name: Starting alpha deploy workflow
        run: |
          echo Starting alpha deploy for PR ${{ github.head_ref }}
      - name: Trigger workflow
        id: curl-circle-ci
        run: |
          curl -d '{"branch": "${{ github.head_ref }}", "parameters": {"deploy_to_dev": true}}' \
          https://circleci.com/api/v2/project/github/yamilmedina/coronavirusapi/pipeline?circle-token=${{ secrets.CIRCLECI_TOKEN }} \
          -H 'Content-Type: application/json' -H 'Accept: application/json'
      - name: Ending alpha deploy workflow with response
        run: echo "The response was ${{ steps.curl-circle-ci.outputs.response }}"