name: pr alpha deploy
on:
  issue_comment:
    types: [created, edited]

jobs:
  deploy-check:
    runs-on: ubuntu-latest
    steps:
      - name: acknowledge deployment request to commenter
        id: check
        uses: khan/pull-request-comment-trigger@master
        with:
          trigger: "/alpha"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}

  deploy:
    runs-on: ubuntu-latest
    needs: deploy-check
    if: needs.deploy-check.outputs.triggered == 'true'
    steps:
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:issue_id
          repository: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: trigger circle ci pipeline
        id: curl-circle-ci
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" \
          -d '{"branch": "${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}", "parameters": {"deploy_to_dev": true}}' \
          "https://circleci.com/api/v2/project/gh/yamilmedina/coronavirusapi/pipeline?circle-token=${{ secrets.CIRCLE_CI_TOKEN }}" 

      - name: output execution status 
        id: comment_pull_request
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:owner/:repo/issues/:issue_id/comments
          owner: ${{ github.owner }}
          repository: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
          body: |
            |
            Alpha release executed, see more info at: 
            https://app.circleci.com/pipelines/github/yamilmedina/coronavirusapi/${{ fromJson(steps.curl-circle-ci.outputs.data).number }}/workflows/${{ fromJson(steps.curl-circle-ci.outputs.data).id }}/
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"