on:
  issue_comment:
    types: [created]
jobs:
  deploy-alpha:
    name: Execute deploy to alpha for pull request comments with rocket
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'gogogo')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'circleci_deploy_alpha'
          subdirectory: 'fastlane'

