name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
 deploy-alpha:
   if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
   runs-on: [ubuntu-latest]
   steps:
     - name: say hello
       if: contains(github.event.comment.body, '/alpha')   # check the comment if it contains the keywords
       run: |
         echo say hello there