name: generate new release tag
on:
  push:
    branches:
      - 'release/*'

jobs:
  gen-new-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch tags
        run: git fetch --tags
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run node file
        run: node run.js     
      - name: Set Tag version
        run: cat chlog*.md

        