name: generate new release tag
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name (ie 6.1.1)'
        required: true

jobs:
  gen-new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch tags
        run: git fetch --tags
      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.versionName }}  
      - name: Initialize bot git config
        run: |
          git config user.name 'Bender Bot'
          git config user.email 'actions-user@users.noreply.github.com'
      - name: Bump version name
        run: sed -ie "s/^VERSION_NAME=.*/VERSION_NAME=${{ github.event.inputs.versionName }}/" chlog.md  
      - name: Use Node.js # start generate chlog
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run node file
        run: node run.js     
      - name: Set Tag version
        run: cat chlog*.md # end generate chlog
      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add chlog.md
          git commit --message "[skip actions] Prepare release ${{ github.event.inputs.versionName }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"  
      - name: Push new release branch
        run: git push origin release/${{ github.event.inputs.versionName }}
      - name: Create PR into master
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/${{ github.event.inputs.versionName }}
          base: master
          title: Release/${{ github.event.inputs.versionName }} into master 🚀
          reviewers: ${{ github.event.issue.user.login }}
          body: |
              Hi human 🤖 ! This PR was created in response manual release workflow execution.
              I've updated the version name for the new release: ${{ steps.make-commit.outputs.commit }}.  
              See more about this version changes at https://github.com/yamilmedina/coronavirusapi/blob/release/${{ github.event.inputs.versionName }}/README.md         
      - name: Create PR into devel
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/${{ github.event.inputs.versionName }}
          base: devel
          title: Release/${{ github.event.inputs.versionName }} into devel 🚀
          reviewers: ${{ github.event.issue.user.login }}
          body: |
              Hi human 🤖 ! This PR was created in response manual release workflow execution.
              I've updated the version name for the new release: ${{ steps.make-commit.outputs.commit }}. 
              See more about this version changes at https://github.com/yamilmedina/coronavirusapi/blob/release/${{ github.event.inputs.versionName }}/README.md         

        