name: generate new changelog
on:
  pull_request:
    branches:
    - 'release/**'
    - 'hotfix/**'

jobs:
  chlog:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v2
      - name: Generate changelog
        run: echo "aaaaaaaaa \n" >> chlog.md
      - name: Push updated changelog
        run: |
          git config --global user.name 'A Bot'
          git config --global user.email 'abot@users.noreply.github.com'
          git add chlog.md
          git commit -am "[skip ci] update changelog for version"
          git push