name: generate new changelog
on:
  push:
    branches:
    - master
    - 'release/**'
  pull_request:
    branches:
    - master
    - 'release/**'

jobs:
  report:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v2
      - name: Generate changelog
        run: echo "aaaaaaaaan" > chlog.md
      - name: Push updated changelog
        run: |
          git config --global user.name 'A Bot'
          git config --global user.email 'abot@users.noreply.github.com'
          git commit -am "[skip ci] update changelog for version"
          git push