name: generate new release tag
on:
  push:
    branches:
      - 'master'

jobs:
  gen-new-tag:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Merge pull request') }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run node file
        run: node run.js     
      - name: Set Tag version
        run: cat chlog*.md
